# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: profumo di frangipani
description: profumo di frangipani - Wunderschöne und leicht zu machende natürliche Rezepte. Vegetarisch und vegan.
